version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nodejs-app
    environment:
      - AWSLOGS_STREAM=task-stream-${CONTAINER_ID}
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: task-logs
        awslogs-stream: ${AWSLOGS_STREAM}

        
